perbaikan

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,41 +1,17 @@
-version: 2.1
+#!/bin/bash -eo pipefail
 
-orbs:
-  docker: circleci/docker@2.2.0
-  go: circleci/go@1.7.3
+# Set environment variables
+DOCKER_USERNAME="imamlabs"
+DOCKER_PASSWORD="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"
+PACKAGE_REGISTRY="ghcr.io"
 
-jobs:
-  test-app:
-    executor:
-      name: go/default
-      tag: '1.15'
-    steps:
-      - checkout
-      - run:
-          name: Run Unit Test
-          command: go test -v -short --count=1 $(go list ./...)
+# Login to GitHub Package Registry
+echo "$DOCKER_PASSWORD" | docker login $PACKAGE_REGISTRY -u $DOCKER_USERNAME --password-stdin
 
-  build-app-karsajobs:
-    executor: docker/docker
-    steps:
-      - checkout
-      - setup_remote_docker
-      - run:
-          name: Build and Push karsajobs Image
-          command: |
-            DOCKER_IMAGE_TAG=$(git rev-parse --short HEAD)
-            docker build -t ghcr.io/$DOCKER_USERNAME/karsajobs:$DOCKER_IMAGE_TAG .
-            echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
-            docker push ghcr.io/$DOCKER_USERNAME/karsajobs:$DOCKER_IMAGE_TAG
-
-
-workflows:
-  ci:
-    jobs:
-      - docker/hadolint:
-          dockerfiles: './Dockerfile'
-      - test-app
-      - build-app-karsajobs:
-          requires:
-            - docker/hadolint
-            - test-app
+# Check if the pull was successful
+if [ $? -eq 0 ]; then
+  echo "Docker login test successful."
+else
+  echo "Docker login test failed."
+  exit 1
+fi
